### ISSUE TITLE
update definition of bot:Site

### ISSUE THREAD

**Issue by mathib** [w3c-lbd-cg/bot#54] opened 2020-02-25 14:20 UTC
As mentioned in https://github.com/w3c-lbd-cg/bot/issues/38. The current definition of `bot:Site` says: 

> Site - Area containing one or more buildings.

A bot:Site is however a subclass of bot:Zone and also corresponds has a spatial 3D extent. Therefore, the definition in BOT should be updated to better reflect this. Proposal:

> Site - a spatial 3D object containing one or more buildings

Maybe there should also be a reference to a standard defining the concept of site in a similar way? I'm unsure if there should be a closer connection to the human concept of "parcel"?

**Comment by GeorgFerdinandSchneider** [comment] 2020-04-03 12:12
closed by https://github.com/w3c-lbd-cg/bot/pull/59

**Comment by mathib** [comment] 2020-04-08 09:58
@GeorgFerdinandSchneider : the definition of bot:Site itself is not (yet?) updated by #59 . Was this discussed in the calls? I'll also add a relevant comment from Rui @deKlerk in the Google spreadsheet with the translations:

> there are sites without buildings, but they're still sites.
> suggestion:
> "Area intended for building, which may contain one or more buildings.":

**Comment by mathib** [comment] 2020-04-08 12:14
Also `bot:Storey `(and maybe even `bot:Building`) text definitions should probably be updated to incorporate the notion of spatial extent

**Comment by maximelefrancois86** [comment] 2020-04-08 15:37
Hi Mathias, 

You are right, I'm reopening this issue.

You're probably right that the definition of Site needs to be updated as well. maybe other. 

What about 


> A part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent, and is intended to contain one or more buildings.

**Comment by mathib** [comment] 2020-04-08 15:41
The new definition for `bot:Site` sounds good for me! Probably should be discussed in the upcoming LBD call. I'll make separate issues for `bot:Building` and `bot:Storey`

**Comment by GeorgFerdinandSchneider** [comment] 2020-04-14 08:52
A comment received by Rui de Klerk @deKlerk: "Area intended for building, which may contain one or more buildings."

Hence I suggest to change the description proposed by Maxime to:

>A part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent, and is intended to contain **zero** or more buildings.

**Comment by mathib** [comment] 2020-04-14 11:54
how can a site that's "intended to contain zero buildings" be a building site? :)

**Comment by GeorgFerdinandSchneider** [comment] 2020-04-14 14:39
I would argue it can. Logically there should also be no probles (we do not have cardinality restrictions)

An empty site prior to construction is a site without a building. Happens often in green field construction

**Comment by mathib** [comment] 2020-04-14 15:57
I just wanted to stress **_intended_** in the definition. This means that it can be empty, but there's at least the intention to make a building on it. Consider an agricultural site: there's no intention to make a building here, thus it's not a building site

**Comment by GeorgFerdinandSchneider** [comment] 2020-04-15 08:15
+1 good you pointed the intended out.

How about:

>A part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent, and is intended to or contains one or more buildings.

**Comment by maximelefrancois86** [comment] 2020-04-23 14:47
This last definition seems perfect to me

> A part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent, and is intended to or contains one or more buildings.

**Comment by GeorgFerdinandSchneider** [comment] 2020-04-23 15:33
Comment received at the W3C LBD CG meeting by Slyvain Marie:
Sylvain MARIE 17:17
Also, ISO already provides: " ISO6707-1 vocabulary "area of land or water where construction work or other development is undertaken". It's more concise ?

**Comment by GeorgFerdinandSchneider** [comment] 2020-04-23 15:34
Current proposal agreed on in W3C LBD CG TelCo @ 23 April 2020, 
confirmed on in W3C LBD CG TelCo @ 19 May 2020:

> A part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent. It is intended to contain or contains one or more buildings.

**Closed as completed** 2020-06-30 16:03 UTC
Labels: Revision of descriptions

**Comment by GeorgFerdinandSchneider** [comment] 2020-07-27 15:26
P Zangeneh commented on 18:06 17. Juli

> What about a building/zone that is not yet built, so it is not yet "inherently located in this world."

answer by @GeorgFerdinandSchneider : We had this discussion. The virtual world is considered a part of this world
